services:
  - type: worker
    name: korean_bot
    env: python
    pythonVersion: 3.11.8
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
